### ISSUE TITLE
Inky frame sleep

### ISSUE THREAD

**Issue by exussum12** [pimoroni/pimoroni-pico#801]
The manual says

https://github.com/pimoroni/pimoroni-pico/blob/main/micropython/modules_py/inky_frame.md#rtc

I get 
`AttributeError: 'module' object has no attribute 'sleep_for'`

when running that code

The example code seems to work 

```
import inky_helper as ih
ih.sleep(minutes)
```

Do I need to update my frame? or example code need updating to follow docs?

**Comment by helgibbons** [comment]
`sleep_for` was a reasonably recent addition I believe - are you using the most the recent Inky Frame MicroPython build from the [releases page](https://github.com/pimoroni/pimoroni-pico/releases)?

**Comment by exussum12** [comment]
I only received it the day before this, assumed it was on latest version. Its mounted on a wall now so next time I update code I will flash and verify

**Comment by iohe** [comment]
Same happened for me. Received Inky Frame 7.3 board today and after writing pimoroni-inky_frame-v1.20.3-micropython.uf2 issue was solved. Thank you very much!

**Comment by helgibbons** [comment]
Good stuff - I'll check with production what version we're preloading on new units and get them to bump it to the newest version if necessary.

**Comment by exussum12** [comment]
Confirmed it was an old version too. Updating resolved

**Comment by daniel-j** [comment]
Did you get sleeping with timer working? I can't get it to work on my Inky Frame 5.7 or 7.3 on battery. It either never wakes up or wakes up instantly. Tested both latest MP release and the C++ examples.

**Comment by exussum12** [comment]
Yeah it works fine for mine. Assume your powering with the JST connection not the USB?

**Comment by thirdr** [comment]
Issue appears to have been resolved. Closing, please reopen if required :)
